name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: setup go
      uses: actions/setup-go@v1
      with:
        go-version: 1.x
    - name: setup env
      run: |
        echo "::set-env name=GOPATH::$(go env GOPATH)"
        echo "::add-path::$(go env GOPATH)/bin"
      shell: bash
    - name: checkout
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
        path: src/github.com/${{ github.repository }}
    - uses: engineerd/setup-kind@v0.3.0
    - run: go test -v ./...
    # - run: sudo cp .circleci/bazel.rc /etc/bazel.bazelrc
    # - run: go get github.com/bazelbuild/bazelisk
    # - run: ~/go/bin/bazelisk query //... --noshow_progress
    # - run: ~/go/bin/bazelisk build //... --noshow_progress
    # - run: |
    #       ~/go/bin/bazelisk test //... --test_output=all --noshow_progress
